### ISSUE TITLE
Anova API Gratitude

### ISSUE THREAD

**Issue by jasonjei** [bogd/anova-oven-api#3]
Dear Bogdan,

I just wanted to thank you for creating and reverse engineering the Anova API. I was trying to reverse engineer it myself but just didn’t have the time to override the certificate pinning as well as having time to understand how the API works. 

Your work has allowed me to proof (do the final rise/fermentation) croissants at home. The difficult thing about proofing croissants is you want the temperature to be under 80 F/26.5 C, but above 70 F/21 C. You also need a bit of a fan and as much humidity as you can afford.

The trouble with the Anova oven is even when you set the temperature to 75 F/24 C, it doesn’t really stay there. It often creeps up to 81-82 F. This is problematic because butter leaks out over 81-82 F/27 C (most butters melt over this temperature). Also, it is better to have a longer fermentation (colder) over a quicker fermentation (hotter) for better flavor, but the temperature needs to be above 70 F/21 C for optimal yeast activity. Croissants gain better flavor with a slower colder fermentation. At 1.9% yeast, I find that 7 hours averaging around 74 F/23 C gives me the best tasting croissants when proofing frozen dough.

I proof frozen croissant dough right before I sleep. From frozen, I would like it to proof warmer in the beginning (and delay the start of the oven to around 1am), and then do a slower colder proof until I wake up so that the croissants are ready to bake (around 7am). You allowed me to sleep so that I can write a script to delay start the oven, and shut off the oven when it gets too hot (over 81 F), and restart the oven when it gets too cold. You have also allowed me to turn off the oven after 2-3 hours of it on without babying it, because the fan sometimes is too strong and pushes the croissants around the sheet pan.

If I were to use a regular proofing box without a fan or water tray, the skin of the croissants would tear during the proof, or be wrinkly without the fan.

Thank you for giving me my sleep back and excellent, flaky tasting croissants for breakfast! I was able to write a fake PID controller to control the final fermentation.  I was able to simulate a $4,000 proofer for the cost of an Anova oven...

Best,
Jason

<img width="600" alt="Screen Shot 2024-10-22 at 9 12 23 AM" src="https://github.com/user-attachments/assets/2c517494-a5f6-4dd4-9bd4-3c7420319eb9">
<img width="600" alt="Screen Shot 2024-10-22 at 9 15 00 AM" src="https://github.com/user-attachments/assets/9c426b51-691c-41db-bd6d-cb6079a91841">
<img width="600" alt="Screen Shot 2024-10-22 at 9 15 33 AM" src="https://github.com/user-attachments/assets/e86cf568-0394-4080-ad06-d02f4140f704">
<img width="600" alt="Screen Shot 2024-10-22 at 9 15 33 AM" src="https://github.com/user-attachments/assets/23c2174a-50b3-4c54-8c03-ac8c932bbcb5">
<img width="600" alt="Screen Shot 2024-10-22 at 9 15 33 AM" src="https://github.com/user-attachments/assets/ce316dc1-9c78-40d5-985c-1bfc200b14c0">

**Comment by bogd** [comment]
Thank you so much for the comment! I am so glad to hear that this helped others, and I would really hope that some day the people at Anova will understand the same thing - that opening up the API can open up some incredible new use cases, that they never even thought about! Unfortunately, based on the way things are going (such as the introduction of a subscription for the sous vide cooker), I don't expect too much... :(

I also started work on this because I wanted some extra sleep - I need to preheat the oven for sourdough bread, but I really do not want to wake up 1hr earlier in the morning to do it. With this, I can start preheating before I wake up, and then I just place the dough in the oven.

I do have to correct you on one thing, though - I did not "create" anything, I just did my best to piece together the information. Building on top of the work of many others (I did my best to credit them in the readme).

On another note, now I want some croissants - those things look delicious! :)

[ Edit - you may want to sanitize the images, since one of them seems to contain your oven ID. I don't think it is an actual security issue (not too much one can do with the ID alone), but better safe... ]

**Comment by bogd** [comment]
I will close this - but once again, I truly do appreciate the kind words. And if anyone else has any other interesting use cases, I would love to hear about them!
